### ISSUE TITLE
2.2版本中mi是啥，是从it中把一部分功能分离出来了吗？

### ISSUE THREAD

**Issue by gdgd8760** [yue19870813/ituuz-x#3]
// 将接口导出
(<any>window).mi || ((<any>window).mi = {});
(<any>window).mi.Framework = Framework;

文档中没有关于mi的说明，案例里面关于it也是有问题的，希望能更新下案例，同时也能更新下文档说明下mi以及添加下关于mi的.d.ts，谢谢

**Comment by yue19870813** [comment]
好的，我稍后会修复一下这个问题


| |
岳斌斌
邮箱：yue19870813@163.com
|

签名由 网易邮箱大师 定制

在2020年04月02日 03:37，gdgd8760 写道：

// 将接口导出
(window).mi || ((window).mi = {});
(window).mi.Framework = Framework;

文档中没有关于mi的说明，案例里面关于it也是有问题的，希望能更新下案例，同时也能更新下文档说明下mi以及添加下关于mi的.d.ts，谢谢

**Comment by yue19870813** [comment]
已经修复并合并到master
